### PR TITLE
[base] upgrade and add packages

### PR DESCRIPTION
**Pull request by CApopsicle**
- upgrade `vue`, `vuex`, `vue-router`,`@cepave/owl-ui` 
- add `validator`

cc @rwu823

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/owl-light/71)

### CODE REVIEW

**Comment by rwu823** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.html, line 13 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC4eCnHM-FSFVYrNa6:-KeC4eCnHM-FSFVYrNa7:b-f9sltk) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L13)):*
> ```HTML
>   <body>
>     <div id="app"></div>
>     <script src="//unpkg.com/vue@2.1.10/dist/vue<%= htmlWebpackPlugin.options.min %>.js"></script>
> ```

vue 最新版為 `2.2.1`

---

*[src/index.html, line 14 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC4znP2vD7IE97xWhL:-KeC4znP2vD7IE97xWhM:b-xhlqj2) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L14)):*
> ```HTML
>     <div id="app"></div>
>     <script src="//unpkg.com/vue@2.1.10/dist/vue<%= htmlWebpackPlugin.options.min %>.js"></script>
>     <script src="//unpkg.com/vuex@2.1.2/dist/vuex.min.js"></script>
> ```

vuex 最新版為 `2.2.1`

---

*[src/index.html, line 15 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC598sWfCeJzzD9rDm:-KeC598sWfCeJzzD9rDn:bx1xu9g) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L15)):*
> ```HTML
>     <script src="//unpkg.com/vue@2.1.10/dist/vue<%= htmlWebpackPlugin.options.min %>.js"></script>
>     <script src="//unpkg.com/vuex@2.1.2/dist/vuex.min.js"></script>
>     <script src="//unpkg.com/vue-router@2.2.1/dist/vue-router.min.js"></script>
> ```

vue-router 最新版為 `2.3.0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by CApopsicle** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/index.html, line 13 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC4eCnHM-FSFVYrNa6:-KeCAQ60KaZigP_U-B3N:b-896fix) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L13)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

vue 最新版為 `2.2.1`
</blockquote></details>

Done.

---

*[src/index.html, line 14 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC4znP2vD7IE97xWhL:-KeCARSwRamDrk5Livtd:b-896fix) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L14)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

vuex 最新版為 `2.2.1`
</blockquote></details>

Done.

---

*[src/index.html, line 15 at r1](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeC598sWfCeJzzD9rDm:-KeCARlcGeA8i6GG3GCc:b-896fix) ([raw file](https://github.com/cepave-f2e/owl-light/blob/f8b28ca72e9bad5047c01789aa816643b1c0268e/src/index.html#L15)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

vue-router 最新版為 `2.3.0`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-:-KeCUJDcN1GqNvVtimtC:bnfp4nl)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeCVezHW7ZhCJ7JxUZb:-KeCVezHW7ZhCJ7JxUZc:bb7p34n) (no related file):*
test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeCVixtYx4n9vUsLcvX:-KeCVixtYx4n9vUsLcvY:bb7p34n) (no related file):*
test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeCVixtYx4n9vUsLcvX:-KeCW7J2QMW9vaSTDsB_:bb7f2mf) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

test
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeCXC8Gw-IsYWk-lH9x:-KeCXC8Hz9v5TaLjjAU_:b-7iykud) (no related file):*
test2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71#-KeCXC8Gw-IsYWk-lH9x:-KeCXX5yF4JAL44fHudc:bucv0rw) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

test2
</blockquote></details>

satisfied! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/owl-light/71)*

**Pull request merged**
